#!/bin/bash
# produce multiple text files separting key parts of original pdf file
# to be run after ex1-sample3

# directory of executables
DIR=".."

# log level
LL=0;

# file to process
infile=sample3

[[ -f "$infile.txt" ]] || { echo "Input file does not exist."; exit 0; }
rm -f $infile.p[0-9]*

echo "$infile.p1: title+subtitle"
$DIR/textblocks $infile.txt -append $infile.p1 -log $LL -copy "{1.1-2}"

echo "$infile.p2: pages"
$DIR/textblocks $infile.txt -append $infile.p2 -log $LL -copy \
		"{1.4-13 3.1-3 4.2-4 4.6-7 5.1-5 6.1 6.8-11 7.1-3 \
		  8.1 8.3-4 9.1-3}"       
$DIR/textblocks $infile.p2 -inplace -log $LL -merge {1.4-5}
$DIR/textblocks $infile.p2 -inplace -log $LL -merge {1.7-12}
$DIR/textblocks $infile.p2 -inplace -log $LL -merge {4.3-4}
$DIR/textblocks $infile.p2 -inplace -log $LL -merge {5.3-4}
$DIR/textblocks $infile.p2 -inplace -log $LL -merge {6.9-10}
$DIR/textblocks $infile.p2 -inplace -log $LL -merge {8.3-4}

echo "$infile.p3: captions"
$DIR/textblocks $infile.txt -append $infile.p3 -log $LL -copy \
		"{2.1-2 3.4 4.1 4.5 5.10-11 6.7 7.4 8.5 9.6-7}"
$DIR/textblocks $infile.p3 -inplace -log $LL -merge {2.1-2}
$DIR/textblocks $infile.p3 -inplace -log $LL -merge {4.1 4.5}
$DIR/textblocks $infile.p3 -inplace -log $LL -merge {5.10-11}
$DIR/textblocks $infile.p3 -inplace -log $LL -merge {9.6-7}

for i in {1..3}; do
    echo $infile.p$i: cleanup
    $DIR/textblocks $infile.p$i -inplace -log $LL -automerge
    $DIR/textblocks $infile.p$i -inplace -log $LL -autorenumber
    $DIR/textblocks $infile.p$i -inplace -log $LL -clean \
		    rs \"\\\([a-z]\\\)- \\+\\\([a-z]\\\):\\1\\2\" \
		    sed "/^\s*$/d" as ".:\\n" sed "s/^ *//g"
    $DIR/textblocks $infile.p$i -inplace -log $LL -clean
done
