#!/bin/bash
# convert pdf to text file
# $infile.out1: clean file retaining block structure
# $infile.out2: clean file with blocks removed

# directory of executables
DIR=".."

# file to process
infile=sample1

[[ -f "$infile.pdf" ]] || { echo "Input file does not exist."; exit 0; }

# delete $infile.* files except $infile.pdf
find . -maxdepth 1 -type f -name "$infile.*" -not -name "$infile.pdf" \
     -exec rm {} \;

# with page layouts
#$DIR/pdfastext -c1 -t1 -m3 -gjpgpdf -i $infile.pdf
# or without
$DIR/pdfastext -c1 -t1 -m2 -i $infile.pdf

# copy selected blocks to output file
$DIR/textblocks $infile.txt -append $infile.out1 -log 3 -copy \
	   "{expand(1.{23,5,1,26,13-14,7,8,24,10-12}) \
	     expand(2.{1,4,5,9,16,19,28}) \
	     expand(3.{60,57,4,1,61,58}) \
	     expand(4.{1,5,7-9}) \
	     expand(5.{3,4,10,6}) \
	     expand(6.{1,3,6-8}) \
	     2.13 3.63 3.48 4.10 5.1}"

# merge some blocks
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {1.23 1.5}
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {1.7-8 1.24}
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {1.11-12}
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {2.5 2.9 2.16}
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {3.57 3.4 3.1 3.61}
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {4.1 4.5}
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {5.4 5.10}
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {6.3 6.6}

# add labels
$DIR/textblocks $infile.out1 -inplace -log 3 -addtext {keywords:} before 1.23

# automerge other blocks (i.e. those across split sentences)
$DIR/textblocks $infile.out1 -inplace -log 3 -automerge

# renumber blocks
$DIR/textblocks $infile.out1 -inplace -log 3 -autorenumber

# clean up: join wo- rds and remove empty lines and then break text into
# sentences after every '.' character
$DIR/textblocks $infile.out1 -inplace -log 3 -clean \
	   rs \"\\\([a-z]\\\)- \\+\\\([a-z]\\\):\\1\\2\" \
	   sed "/^\s*$/d" as ".:\\n" sed "s/^ *//g"

# add meta information into a new output file
$DIR/textblocks $infile.out1 -overwrite $infile.meta -log 3 \
		-clean addmeta before

# produce clean output with block labels removed
$DIR/textblocks $infile.out1 -overwrite $infile.out2 -log 3 -clean 

