#!/bin/bash
# produce multiple text files separting key parts of original pdf file
# to be run after ex1-sample1

# directory of executables
DIR=".."

# log level
LL=0;

# file to process
infile=sample1

[[ -f "$infile.txt" ]] || { echo "Input file does not exist."; exit 0; }
rm -f $infile.p[0-9]*

echo "$infile.p1: keywords"
$DIR/textblocks $infile.txt -append $infile.p1 -log $LL -copy "{1.23 1.5}"
$DIR/textblocks $infile.p1 -inplace -log $LL -merge {1.23 1.5}

echo "$infile.p2: title+abstract"
$DIR/textblocks $infile.txt -append $infile.p2 -log $LL -copy "{1.1 1.26}"

echo "$infile.p3: inset"
$DIR/textblocks $infile.txt -append $infile.p3 -log $LL -copy "{1.13-14}"

echo "$infile.p4: pages"
$DIR/textblocks $infile.txt -append $infile.p4 -log $LL -copy \
		"{expand(1.{7,8,24,10-12}) expand(2.{1,4,5,9,16,19,28}) \
		  expand(3.{60,57,4,1,61,58}) expand(4.{1,5,7-9}) \
		  expand(5.{3,4,10,6}) expand(6.{1,3,6-8})}"
$DIR/textblocks $infile.p4 -inplace -log $LL -merge {1.7-8 1.24}
$DIR/textblocks $infile.p4 -inplace -log $LL -merge {1.11-12}
$DIR/textblocks $infile.p4 -inplace -log $LL -merge {2.5 2.9 2.16}
$DIR/textblocks $infile.p4 -inplace -log $LL -merge {3.57 3.4 3.1 3.61}
$DIR/textblocks $infile.p4 -inplace -log $LL -merge {4.1 4.5}
$DIR/textblocks $infile.p4 -inplace -log $LL -merge {5.4 5.10}
$DIR/textblocks $infile.p4 -inplace -log $LL -merge {6.3 6.6}

echo "$infile.p5: captions"
$DIR/textblocks $infile.txt -append $infile.p5 -log $LL -copy \
		"{2.13 3.63 3.48 4.10 5.1}"

echo "$infile.p6: references"
$DIR/textblocks $infile.txt -append $infile.p6 -log $LL -copy "{6.4 6.10}"

for i in {1..6}; do
    echo $infile.p$i: cleanup
    $DIR/textblocks $infile.p$i -inplace -log $LL -automerge
    $DIR/textblocks $infile.p$i -inplace -log $LL -autorenumber
    $DIR/textblocks $infile.p$i -inplace -log $LL -clean \
		    rs \"\\\([a-z]\\\)- \\+\\\([a-z]\\\):\\1\\2\" \
		    sed "/^\s*$/d" as ".:\\n" sed "s/^ *//g"
    $DIR/textblocks $infile.p$i -inplace -log $LL -clean
done
