#!/bin/bash
# generate list of keywords from index in a book

# directory of executables
DIR=".."

# file to process
infile=index

[[ -f "$infile.pdf" ]] || { echo "Input file does not exist."; exit 0; }

# delete $infile.* files except $infile.pdf
find . -maxdepth 1 -type f -name "$infile.*" -not -name "$infile.pdf" \
     -not -name "$infile-p*.jpg" -exec rm {} \;

# with page layouts
#$DIR/pdfastext -c1 -t1 -m2 -b0 -gjpgpdf -i $infile.pdf
$DIR/pdfastext -c1 -t1 -m2 -q -b0 -i $infile.pdf

# copy file and delete extra blocks
# setting -log 0 suppresses all messages
cp $infile.txt $infile.out1
$DIR/textblocks $infile.out1 -inplace -log 0 -delete \
		"{1.1-3 1.7 2.1 2.2 3.1 3.4 4.1 4.2 5.1 5.6 6.1 6.2 7.1 7.4 \
		  8.1 8.2 9.1 9.4 10.1 10.2 11.1 11.4 12.1 12.2 13.1 13.4 \
		  14.1 14.2 15.1 15.5 16.1 16.2 17.1 17.4 18.1 18.2 19.1 19.4 \
		  20.1 20.2 21.1 21.4 22.1 22.2 23.1 23.5 24.1 24.2 25.1 25.4 \
		  26.1 26.2 27.1 27.5 28.1 28.2 29.1 29.4 30.1 30.2 31.1 31.4 \
		  32.1 32.2 33.1 33.5 34.1 34.2 35.1 35.4 36.1 36.2 37.1 37.4 \
		  38.1 38.2 39.1 39.4 40.1 40.2 41.1 41.4 42.1 42.2 43.1 43.4 \
		  44.1 44.2 45.1 45.4 46.1 46.2 47.1 47.4 48.1 48.2 49.1 49.4 \
		  50.1 50.2 51.1 51.5 52.1 52.2 53.1 53.6}"

# produce clean output with block labels removed
$DIR/textblocks $infile.out1 -overwrite $infile.out2 -log 3 -clean 

cat $infile.out2 | tr -dc '[:print:]\n' | \
    sed 's/-/ /g' | sed 's/,//g' | sed 's/[0-9]\{2,4\}[A-Z]*//g' | \
    sed 's/^\s*//;s/\s*$//' | sed 's/^[A-Z]$//' | sed 's/ \+/ /g' | \
    sed '/^\s*$/d' > $infile.out3
rm -fr $infile.out2
mv $infile.{out3,out2}
