#!/bin/bash

# file to process
infile=sample1

# with page layouts
#pdfastext -c1 -t1 -m3 -i -m3 -gjpgpdf $infile.pdf
# or without
pdfastext -c1 -t1 -m2 -i $infile.pdf

# copy selected blocks to output file
textblocks $infile.txt -append $infile.out1 -log 3 -copy \
	   "{expand(1.{1,26,7,8,24,10,11,12}) \
	    expand(2.{1,4,5,9,16,19,28})     \
	     expand(3.{60,57,4,1,61,58})      \
	     expand(4.{1,5,7-9})	      \
	     expand(5.{3,4,10,6})	      \
	     expand(6.{1,3,6-8})}"	      

# merge some blocks
textblocks $infile.out1 -inplace -log 3 -merge "1.7-8" 
textblocks $infile.out1 -inplace -log 3 -merge "1.11-12" 
textblocks $infile.out1 -inplace -log 3 -merge {3.57 3.4}

# automerge those blocks with split sentences
textblocks $infile.out1 -inplace -log 3 -automerge

# renumber blocks
textblocks $infile.out1 -inplace -log 3 -autorenumber

# clean up: join wo- rds and remove empty lines and then break text into
# sentences after every '.' character
textblocks $infile.out1 -inplace -log 3 -clean \
	   rs \"\\\([a-z]\\\)- \\+\\\([a-z]\\\):\\1\\2\" \
	   sed "/^\s*$/d" as ".:\\n" sed "s/^ *//g"

# add meta information into a new output file
textblocks $infile.out1 -overwrite $infile.out2 -log 3 -clean addmeta before

# also produce output with block labels removed
textblocks $infile.out1 -overwrite $infile.out11 -log 3 -clean 

# copy inset and figure captions
textblocks $infile.txt -overwrite $infile.out3 -log 3 -copy \
	   {1.13-14 2.13 3.63 3.48 4.10 5.1}

# copy references
textblocks $infile.txt -overwrite $infile.out4 -log 3 -copy {6.4 6.10}


exit 0

INSET

1.13 1.14

FIG CAPTIONS

Fig1: 2.13
Fig2: 3.63
Fig3: 3.48
Fig4: 4.10
Fig5: 5.1

PAGE 1: 1 26 7+8 24 10 11+12 

PAGE 2: 1 4 5 9 16 19 28

PAGE 3: 60 57+4 1 61 58 

PAGE 4: 1 5 7-9  

PAGE 5: 3 4 10 6

PAGE 6: 1 3 6-8

REFERECNES: 6.4 6.10


