#!/bin/bash
# convert pdf to text file
# $infile.out1: clean file retaining block structure
# $infile.out2: clean file with blocks removed

# directory of executables
DIR=".."

# file to process
infile=sample4

[[ -f "$infile.pdf" ]] || { echo "Input file does not exist."; exit 0; }

# delete $infile.* files except $infile.pdf
find . -maxdepth 1 -type f -name "$infile.*" -not -name "$infile.pdf" \
     -exec rm {} \;

# with page layouts
#$DIR/pdfastext -c1 -t1 -m3 -gjpgpdf -i $infile.pdf
# or without
$DIR/pdfastext -c1 -t1 -m2 -i $infile.pdf

# copy selected blocks to output file
$DIR/textblocks $infile.txt -append $infile.out1 -log 3 -copy \
	   "{expand(1.{3,5,7,6,8,10-12}) 2.36-43 \
	     expand(3.{10,15,16,20,21}) 4.13-16 5.2-8 6.2-5 7.2 \
	     3.9 3.19 3.14 4.12 2.2-34}"

# merge some blocks
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {1.7 1.6}
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {2.2-34}

# automerge other blocks (i.e. those across split sentences)
$DIR/textblocks $infile.out1 -inplace -log 3 -automerge

# renumber blocks
$DIR/textblocks $infile.out1 -inplace -log 3 -autorenumber

# clean up: join wo- rds and remove empty lines and then break text into
# sentences after every '.' character
$DIR/textblocks $infile.out1 -inplace -log 3 -clean \
	   rs \"\\\([a-z]\\\)- \\+\\\([a-z]\\\):\\1\\2\" \
	   sed "/^\s*$/d" as ".:\\n" sed "s/^ *//g"

# add meta information into a new output file
$DIR/textblocks $infile.out1 -overwrite $infile.meta -log 3 \
		-clean addmeta before

# produce clean output with block labels removed
$DIR/textblocks $infile.out1 -overwrite $infile.out2 -log 3 -clean 
