#!/bin/bash
# convert pdf to text file
# $infile.out1: clean file retaining block structure
# $infile.out2: clean file with blocks removed

# directory of executables
DIR=".."

# file to process
infile=sample5

[[ -f "$infile.pdf" ]] || { echo "Input file does not exist."; exit 0; }

# delete $infile.* files except $infile.pdf
find . -maxdepth 1 -type f -name "$infile.*" -not -name "$infile.pdf" \
     -exec rm {} \;

# with page layouts
#$DIR/pdfastext -c1 -t1 -m3 -gjpgpdf -i $infile.pdf
# or without
$DIR/pdfastext -c1 -t1 -m2 -i $infile.pdf

# copy selected blocks to output file
$DIR/textblocks $infile.txt -append $infile.out1 -log 3 -copy \
	   "{1.1 1.4-5 2.2-3 1.14-15 1.13 \
	     2.4 2.7 expand(3.{2,5,7,8,4,6,22}) expand(4.{176,178,183}) \
	     expand(5.{12,19,30,48,10,38,27,51}) 6.2-4 6.7 \
	     expand(7.{3,2,105,106}) expand(8.{2,10,16,5-8}) \
	     expand(9.{21,25,29,2,10,14,15,20,23}) 10.5 10.13 10.3 \
	     11.5 11.4 11.7-8 12.4 12.3 12.6-7 13.3 13.2 14.3-5 14.2 \
	     16.3-4 16.2 17.3-6 17.2 18.4-6 18.3 19.5 19.2 19.3 \
	     expand(20.{3,8,10,12,2,5,4}) 2.6 3.3 6.6 9.16 10.4 10.2 \
	     11.3 11.2 12.2 13.4 14.6 15.2 15.3 16.5 18.2 19.4 4.2 7.4}"

# merge some blocks
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {3.4 3.6}
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {9.14-15}
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {20.10 20.12}
$DIR/textblocks $infile.out1 -inplace -log 3 -merge {20.5 20.4}

# automerge other blocks (i.e. those across split sentences)
$DIR/textblocks $infile.out1 -inplace -log 3 -automerge

# renumber blocks
$DIR/textblocks $infile.out1 -inplace -log 3 -autorenumber

# clean up: join wo- rds and remove empty lines and then break text into
# sentences after every '.' character
$DIR/textblocks $infile.out1 -inplace -log 3 -clean \
	   rs \"\\\([a-z]\\\)- \\+\\\([a-z]\\\):\\1\\2\" \
	   sed "/^\s*$/d" as ".:\\n" sed "s/^ *//g"

# add meta information into a new output file
$DIR/textblocks $infile.out1 -overwrite $infile.meta -log 3 \
		-clean addmeta before

# produce clean output with block labels removed
$DIR/textblocks $infile.out1 -overwrite $infile.out2 -log 3 -clean 
