#!/bin/bash
# produce multiple text files separting key parts of original pdf file
# to be run after ex1-sample5

# directory of executables
DIR=".."

# log level
LL=0;

# file to process
infile=sample5

[[ -f "$infile.txt" ]] || { echo "Input file does not exist."; exit 0; }
rm -f $infile.p[0-9]*

echo "$infile.p1: title+abstract+summary"
$DIR/textblocks $infile.txt -append $infile.p1 -log $LL -copy \
		"{1.1 1.4-5 2.2-3}"

echo "$infile.p2: pages"
$DIR/textblocks $infile.txt -append $infile.p2 -log $LL -copy \
	   "{1.14-15 1.13 2.4 2.7 expand(3.{2,5,7,8,4,6,22}) \
	     expand(4.{176,178,183}) expand(5.{12,19,30,48,10,38,27,51}) \
	     6.2-4 6.7 expand(7.{3,2,105,106}) expand(8.{2,10,16,5-8}) \
	     expand(9.{21,25,29,2,10,14,15,20,23}) 10.5 10.13 10.3 \
	     11.5 11.4 11.7-8 12.4 12.3 12.6-7 13.3 13.2 14.3-5 14.2 \
	     16.3-4 16.2 17.3-6 17.2 18.4-6 18.3 19.5 19.2 19.3 \
	     expand(20.{3,8,10,12,2,5,4})}"
$DIR/textblocks $infile.p2 -inplace -log $LL -merge {3.4 3.6}
$DIR/textblocks $infile.p2 -inplace -log $LL -merge {9.14-15}
$DIR/textblocks $infile.p2 -inplace -log $LL -merge {20.10 20.12}
$DIR/textblocks $infile.p2 -inplace -log $LL -merge {20.5 20.4}

echo "$infile.p3: captions"
$DIR/textblocks $infile.txt -append $infile.p3 -log $LL -copy \
		"{2.6 3.3 6.6 9.16 10.4 10.2 11.3 11.2 12.2 13.4\
		  14.6 15.2 15.3 16.5 18.2 19.4 4.2 7.4}"

echo "$infile.p4: captions"
$DIR/textblocks $infile.txt -append $infile.p4 -log $LL -copy \
		"{20.15 20.14 21.2 21.4}"

echo "$infile.p5: references"
$DIR/textblocks $infile.txt -append $infile.p5 -log $LL -copy \
		"{20.15 20.14 21.2 21.4}"

for i in {1..5}; do
    echo $infile.p$i: cleanup
    $DIR/textblocks $infile.p$i -inplace -log $LL -automerge
    $DIR/textblocks $infile.p$i -inplace -log $LL -autorenumber
    $DIR/textblocks $infile.p$i -inplace -log $LL -clean \
		    rs \"\\\([a-z]\\\)- \\+\\\([a-z]\\\):\\1\\2\" \
		    sed "/^\s*$/d" as ".:\\n" sed "s/^ *//g"
    $DIR/textblocks $infile.p$i -inplace -log $LL -clean
done

