#!/bin/bash
# keywords locator, use whole txt paper
# evaluate 
# modified ex3-sample1 script, produce results for the paper

# elapsed time
etime() { echo "$(($(date -u +%s)-$1))"; }

# directory of executables
DIR=".."

# output file
of=$(basename $0)

# file to process
infile=${of/ex5-}
#f=$infile.txt
f=$infile.out2
[[ -f "$f" ]] || { echo "File $f not found."; exit 0; }

# find most frequent words, remove stopwords
# output: word, occurrences
S=3   # shorter words to discard
K=202 # the first K words to keep

## single words
stime1="$(date -u +%s)"
echo "searching single words"
w1=$($DIR/texttoinfo -bow -nomsg -ef $DIR/en-stopwords -es "block" -w $S -$K $f)
WL1=$(while read -r n w; do
	  cat $f | tr '.,?:;!-' ' ' | \
	      awk -v w="$w" -v n="$n" '{if($0 ~ p){for(i=1;i<=NF;i++) \
	     {T++;if(tolower($i)==tolower(w)){c[j++]=T-P-1;P=T}}} \
	      else {T+=NF}} END{if(j==0)exit 1;for(i in c)m+=c[i];m/=j; \
	      for(i in c)m2+=(c[i]-m)**2;m2/=(m*m*(j-1)); \
	      printf "%s,%d,%.3f\n",w,n,int(m2*1e3)/1e3}'
      done < <(echo "$w1") | sort -t, -nr -k2,2 -k3,3 | column -t -s',')
n1=$(echo "$WL1" | wc -l)
echo "$WL1" >| $of.w1
WL1=$(echo "$WL1" | awk '{print $1}')
echo "$n1/$n1   > $of.w1 ($(etime $stime1)s)"

## 2-word phrases
stime2="$(date -u +%s)"
echo "searching 2-word phrases"
n1=$(echo "$WL1" | wc -l)
text=$(cat $f | tr '\n' ' ' | tr -s ' ' | tr '[:upper:]' '[:lower:]')
c=0
ll=
while read -r i; do
    printf "\r%d/%d   " $((++c)) $n1
    l1=$(echo "$text" | grep -Eo -i "${i}[\ ]*\b\w+\b")
    l2=$(echo "$text" | grep -Eo -i "\b\w+\b[\ ]*${i}")
    ll=$(paste -sd '\n' <(echo "$ll") <(echo "$l1") <(echo "$l2"))
done < <(echo "$WL1")
WL2=$(echo "$ll" | sed '/^[ ]*$/d' | awk '{$1=$1};1' | \
	  sort | uniq -c | sort -nr | awk '$1>0{print}')
echo "$WL2" >| $of.w2
echo "> $of.w2 ($(etime $stime2)s)"

## 3-word phrases
stime3="$(date -u +%s)"
echo "searching 3-word phrases"
n2=$(echo "$WL2" | wc -l)
c=0
ll=
while read -r i; do
    i=$(echo "$i" | awk '{$1="";print $0}')
    printf "\r%d/%d   " $((++c)) $n2
    l1=$(echo "$text" | grep -Eo -i "${i}[\ ]*\b\w+\b")
    l2=$(echo "$text" | grep -Eo -i "\b\w+\b[\ ]*${i}")
    ll=$(paste -sd '\n' <(echo "$ll") <(echo "$l1") <(echo "$l2"))
done < <(echo "$WL2")
WL3=$(echo "$ll" | sed '/^[ ]*$/d' | awk '{$1=$1};1' | \
	  sort | uniq -c | sort -nr | awk '$1>0{print}')
echo "$WL3" >| $of.w3
echo "> $of.w3 ($(etime $stime3)s)"

## 4-word phrases
stime4="$(date -u +%s)"
echo "searching 4-word phrases"
n3=$(echo "$WL3" | wc -l)
c=0
ll=
while read -r i; do
    i=$(echo "$i" | awk '{$1="";print $0}' | awk '{$1=$1};1')
    printf "\r%d/%d   " $((++c)) $n3
    l1=$(echo "$text" | grep -Eo -i "${i}[\ ]*\b\w+\b")
    l2=$(echo "$text" | grep -Eo -i "\b\w+\b[\ ]*${i}")
    ll=$(paste -sd '\n' <(echo "$ll") <(echo "$l1") <(echo "$l2"))
done < <(echo "$WL3")
WL4=$(echo "$ll" | sed '/^[ ]*$/d' | awk '{$1=$1};1' | \
	  sort | uniq -c | sort -nr | awk '$1>0{print}')
echo "$WL4" >| $of.w4
echo "> $of.w4 ($(etime $stime4)s)"
echo "Time total: $(etime $stime1)s"

# check if exactly N-word phrases selected
#while read -r i; do
#    j=$(echo "$i" | wc -w)
#    [[ "$j" == "5" ]] || echo $i
#done < <(echo "$WL4")
